import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/shared/Navbar/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="w-[95%] sm:w-[90%] md:w-[90%] lg:w-[85%] xl:w-[80%] 2xl:w-[1440px] mx-auto">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
